name: Python CI
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: ["main"]

jobs:
  # Job 1 (parallel)
  secrets_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret is ${{ secrets.MY_SECRET }}"
      - run: echo "Variable is ${{ vars.MY_VAR }}"

  # Job 2 (parallel)
  run_bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from Bash!"

  # Job 3 (sequential - waits for above)
  run_python:
    needs: [secrets_check, run_bash]   # 👈 key line
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: python sample_python.py

