name: Python CI

on:
  push:
    branches: [ "main" ]

jobs:
  secrets_check:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret
        run: echo "Secret is ${{ secrets.MY_SECRET }}"

      - name: Get Variable
        run: echo "Variable is ${{ vars.MY_VAR }}"

  run_bash:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "Hello, GitHub Actions!"

  run_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9, 3.12, 3.11 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
         python-version: ${{ matrix.python-version }}
      - name: Run script
        run: python sample_python.py

